"""documents add scope and access_level

Revision ID: fb1d5f2436bb
Revises: fa270b85f4b4
Create Date: 2026-08-15 21:15:42.999260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1d5f2436bb'
down_revision: Union[str, Sequence[str], None] = 'fa270b85f4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_conversation_root_name', 'conversation', 'messages', ['root_message_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conversation_root_name', 'conversation', type_='foreignkey')
    # ### end Alembic commands ###
